name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Publish to MavenCentral
        run: |
          VERSION="${{ github.sha }}"
          VERSION="${VERSION:0:10}-SNAPSHOT"
          ./gradlew publishToMavenCentral -Pversion=$VERSION
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
